<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\Recruiter;
use App\Model\Jobseeker;
use App\Model\Scout;
use Auth;
use App\Http\Controllers\API\V1\BaseController;

class NotificationController extends BaseController
{
 
    //recruiter noti
    //generated by Yan Lynn Aung and Su Sandy Aung
    //21.8.2020 (fri)
    public function getRecruiterFavCount()
    {
        $fav_count = 0;
		if(Auth::user())
        {
            $recruiterId = BaseController::getLoginRecruiterID();
			$favJobseekerId = Recruiter::where('id',$recruiterId)->select('favourite_jobseeker_ids')->value('favourite_jobseeker_ids');
			if($favJobseekerId)
			{
				$favJobseekerList = explode(',',$favJobseekerId);
				$fav_count = count($favJobseekerList);
			}	
		}
		return response()->json($fav_count);
    }

    //generated by Yan Lynn Aung and Su Sandy Aung
    //21.8.2020 (fri)
    public function getApplicantCount()
    {
        $applicant_count = 0;
		if(Auth::user())
        {
            $recruiterId = BaseController::getLoginRecruiterID();
            $apply_list = Recruiter::join('jobs','jobs.recruiter_id','recruiters.id')
                                        ->join('job_applies','job_applies.job_id','jobs.id')
                                        ->where('recruiters.id',$recruiterId)
                                        ->where('job_applies.job_apply_status','検討中')
                                        ->get();

            $applicant_count = count($apply_list);
                             	
		}
		return response()->json($applicant_count);
    }

    //generated by Yan Lynn Aung and Su Sandy Aung
    //21.8.2020 (fri)
    public function getScoutedCount()
    {
        $scouted_count = 0;
		if(Auth::user())
        {
            $recruiterId = BaseController::getLoginRecruiterID();
            $scouted_list = Recruiter::join('scouts','scouts.recruiter_id','recruiters.id')
                                        ->where('scouts.scout_status','回答待ち')
                                        ->where('recruiters.id',$recruiterId)
                                        ->get();

            $scouted_count = count($scouted_list);
                             	
		}
		return response()->json($scouted_count);
    }
    //recruiter noti


    //jobseeker noti
    //generated by Yan Lynn Aung and Su Sandy Aung
    //21.8.2020 (fri)
    public function scoutedCount()
	{
	
		$count = 0;
		$id = $this->getLoginJobseekerID();
		$scouts = Scout::where('jobseeker_id',$id)->where('scout_status','回答待ち')->get();
		if(sizeof($scouts)){
			$count = Count($scouts);
		}
		return $count;
		
    }
    
    //generated by Yan Lynn Aung and Su Sandy Aung
    //21.8.2020 (fri)	
	public function getJobseekerFavCount()
	{
		$favCount = 0;
		if(Auth::user())
        {
            $jobseekerId = BaseController::getLoginJobseekerID();
            $favJobId = Jobseeker::where('id',$jobseekerId)->select('favourite_job_ids')->value('favourite_job_ids');
         
			if($favJobId)
			{
				$favJobList = explode(',',$favJobId);
				$favCount = count($favJobList);
			}
			
		}
		return response()->json($favCount);
    }
    //jobseeker noti
    
    public function userImg()
    {
        if(Auth::user()->role_id == 2){
            $recruiterId = BaseController::getLoginRecruiterID();
            $get_recruiter_number = Recruiter::where('id',$recruiterId)->select('logo')->value('logo');
            return response()->json($get_recruiter_number);
        }
        else if(Auth::user()->role_id == 3){
            $jobseekerId = BaseController::getLoginJobseekerID();
            $get_face_image = Jobseeker::where('id',$jobseekerId)->select('face_image')->value('face_image');
            return response()->json($get_face_image);
        }
    }
    public function userInfo()
    {
        if(Auth::user()->role_id == 2){
            $recruiterId = BaseController::getLoginRecruiterID();
            $get_recruiter = Recruiter::where('id',$recruiterId)->get();
            return response()->json($get_recruiter);
        }
        else if(Auth::user()->role_id == 3){
            $jobseekerId = BaseController::getLoginJobseekerID();
            $get_jobseeker = Jobseeker::where('id',$jobseekerId)->get();
            return response()->json($get_jobseeker);
        }
    }
    
}
