<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            array('city_name' => 'アメリカ合衆国（米国）','country_name' => 'アメリカ合衆国（米国）','continent_name' => 'アメリカ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'カナダ','country_name' => 'カナダ','continent_name' => 'カナダ・メキシコ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ハワイ','country_name' => 'ハワイ','continent_name' => 'ハワイ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'アルゼンチン','country_name' => 'アルゼンチン','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'アルバ','country_name' => 'アルバ','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'アンティグア・バーブーダ','country_name' => 'アンティグア・バーブーダ','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ウルグアイ','country_name' => 'ウルグアイ','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'エクアドル','country_name' => 'エクアドル','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'エルサルバドル','country_name' => 'エルサルバドル','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'キューバ','country_name' => 'キューバ','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'キュラソー','country_name' => 'キュラソー','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'グアテマラ','country_name' => 'グアテマラ','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ケイマン諸島','country_name' => 'ケイマン諸島','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'コスタリカ','country_name' => 'コスタリカ','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'コロンビア','country_name' => 'コロンビア','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ジャマイカ','country_name' => 'ジャマイカ','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'チリ','country_name' => 'チリ','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ドミニカ共和国','country_name' => 'ドミニカ共和国','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'トリニダード・トバゴ','country_name' => 'トリニダード・トバゴ','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ニカラグア','country_name' => 'ニカラグア','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'パナマ','country_name' => 'パナマ','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'バハマ','country_name' => 'バハマ','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'バミューダ','country_name' => 'バミューダ','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'パラグアイ','country_name' => 'パラグアイ','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ブラジル','country_name' => 'ブラジル','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ベリーズ','country_name' => 'ベリーズ','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ペルー','country_name' => 'ペルー','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ボリビア','country_name' => 'ボリビア','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ホンジュラス','country_name' => 'ホンジュラス','continent_name' => 'カリブ・中南米','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'アイスランド','country_name' => 'アイスランド','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'アイルランド','country_name' => 'アイルランド','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'アゼルバイジャン','country_name' => 'アゼルバイジャン','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'アルバニア','country_name' => 'アルバニア','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'アルメニア','country_name' => 'アルメニア','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'イギリス','country_name' => 'イギリス','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'イタリア','country_name' => 'イタリア','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ウクライナ','country_name' => 'ウクライナ','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'エストニア','country_name' => 'エストニア','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'オーストリア','country_name' => 'オーストリア','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'オランダ','country_name' => 'オランダ','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'キプロス','country_name' => 'キプロス','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ギリシャ','country_name' => 'ギリシャ','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'クロアチア','country_name' => 'クロアチア','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ジブラルタル','country_name' => 'ジブラルタル','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ジョージア','country_name' => 'ジョージア','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'スイス','country_name' => 'スイス','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'スウェーデン','country_name' => 'スウェーデン','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'スペイン','country_name' => 'スペイン','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'スロバキア','country_name' => 'スロバキア','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'スロベニア','country_name' => 'スロベニア','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'セルビア','country_name' => 'セルビア','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'チェコ','country_name' => 'チェコ','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'デンマーク','country_name' => 'デンマーク','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ドイツ','country_name' => 'ドイツ','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'トルコ','country_name' => 'トルコ','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ノルウェー','country_name' => 'ノルウェー','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ハンガリー','country_name' => 'ハンガリー','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'フィンランド','country_name' => 'フィンランド','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'フランス','country_name' => 'フランス','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ブルガリア','country_name' => 'ブルガリア','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ベラルーシ','country_name' => 'ベラルーシ','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ベルギー','country_name' => 'ベルギー','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ポーランド','country_name' => 'ポーランド','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ボスニア・ヘルツェゴビナ','country_name' => 'ボスニア・ヘルツェゴビナ','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ポルトガル','country_name' => 'ポルトガル','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'マルタ','country_name' => 'マルタ','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'モルドバ','country_name' => 'モルドバ','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'モンテネグロ','country_name' => 'モンテネグロ','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ラトビア','country_name' => 'ラトビア','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'リトアニア','country_name' => 'リトアニア','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ルーマニア','country_name' => 'ルーマニア','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ルクセンブルク','country_name' => 'ルクセンブルク','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ロシア','country_name' => 'ロシア','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '北マケドニア','country_name' => '北マケドニア','continent_name' => 'ヨーロッパ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'イスラエル','country_name' => 'イスラエル','continent_name' => '中東・アフリカ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ナイジェリア','country_name' => 'ナイジェリア','continent_name' => '中東・アフリカ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '南アフリカ','country_name' => '南アフリカ','continent_name' => '中東・アフリカ','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '北海道','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '青森県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '岩手県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '宮城県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '秋田県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '山形県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '福島県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '茨城県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '栃木県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '群馬県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '埼玉県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '千葉県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '東京都','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '神奈川県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '新潟県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '富山県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '石川県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '福井県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '山梨県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '長野県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '岐阜県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '静岡県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '愛知県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '三重県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '滋賀県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '京都府','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '大阪府','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '兵庫県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '奈良県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '和歌山県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '鳥取県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '島根県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '岡山県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '広島県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '山口県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '徳島県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '香川県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '愛媛県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '高知県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '福岡県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '佐賀県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '長崎県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '熊本県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '大分県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '宮崎県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '鹿児島県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '沖縄県','country_name' => '日本','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '韓国','country_name' => '韓国','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '北朝鮮','country_name' => '北朝鮮','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '中華民国（台湾）','country_name' => '中華民国（台湾）','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => '中華人民共和国','country_name' => '中華人民共和国','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'モンゴル','country_name' => 'モンゴル','continent_name' => '東アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'インド','country_name' => 'インド','continent_name' => '東南アジア・南アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'インドネシア','country_name' => 'インドネシア','continent_name' => '東南アジア・南アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'カンボジア','country_name' => 'カンボジア','continent_name' => '東南アジア・南アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'シンガポール','country_name' => 'シンガポール','continent_name' => '東南アジア・南アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'スリランカ','country_name' => 'スリランカ','continent_name' => '東南アジア・南アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'タイ','country_name' => 'タイ','continent_name' => '東南アジア・南アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'フィリピン','country_name' => 'フィリピン','continent_name' => '東南アジア・南アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ベトナム','country_name' => 'ベトナム','continent_name' => '東南アジア・南アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'マレーシア','country_name' => 'マレーシア','continent_name' => '東南アジア・南アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ミャンマー','country_name' => 'ミャンマー','continent_name' => '東南アジア・南アジア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'オーストラリア','country_name' => 'オーストラリア','continent_name' => 'オスアニア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'アデレード','country_name' => 'アデレード','continent_name' => 'オスアニア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
            array('city_name' => 'ニュージーランド','country_name' => 'ニュージーランド','continent_name' => 'オスアニア','created_at' => Carbon::now(),'updated_at' => Carbon::now(),),
        ];
        DB::table('countries')->insert($data);
    }
}
